# Generated by Django 5.0.1 on 2024-01-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    # Пометка initial указывает, что эта миграция — первая в приложении.
    initial = True

    dependencies = [
        # В dependencies хранится список миграций, без которых нельзя применить
        # текущую. У следующей миграции в этом приложении будет dependencies =
        # [('movies', '0001_create_content_schema')]

        # Если описанные вами изменения связаны с таблицами из других приложений,
        # Django добавит в этот список миграции, в которых создаются те таблицы.

        # Так как описанные вами таблицы не зависят от таблиц из других приложений
        # или от предыдущих миграций, сейчас этот список пуст.
    ]

    operations = [

        # В operations последовательно описаны изменения, которые предстоит пережить
        # базе при применении этой миграции.

        # С расшифровкой всех возможных операций можно ознакомиться в документации на
        # английском (https://docs.djangoproject.com/en/3.1/ref/migration-operations/)

        migrations.RunSQL(
            sql="create schema if not exists content;",

            reverse_sql="drop schema if exists content;",
        )
    ]
