# Generated by Django 5.0.1 on 2024-01-19 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_create_tables'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            create type content.film_type_enum as enum ('movie', 'tv_show');
            alter table content.film
                alter column film_type type content.film_type_enum using film_type::content.film_type_enum;

            create type content.person_role_enum as enum ('actor', 'writer', 'director');
            alter table content.person_film
                alter column person_role type content.person_role_enum using person_role::content.person_role_enum;

            commit;
            """,

            reverse_sql="""
            alter table content.film alter column film_type type text;
            drop type content.film_type_enum;

            alter table content.person_film alter column person_role type text;
            drop type content.person_role_enum;

            commit;
            """,
        )
    ]
